name: Daily TVBox Sync

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Backup workflow
        run: |
          mkdir -p /tmp/workflow
          cp .github/workflows/update.yml /tmp/workflow/update.yml

      - name: Download upstream
        run: |
          git clone --depth 1 https://github.com/25175/tvyuan.git /tmp/upstream

      - name: Replace files
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
          cp -a /tmp/upstream/. .

      - name: Restore workflow
        run: |
          mkdir -p .github/workflows
          cp /tmp/workflow/update.yml .github/workflows/update.yml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "auto update from 25175/tvyuan"

      - name: Push changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
